### ISSUE TITLE
Remove unused dependency on EMF Query

### ISSUE THREAD

**Issue by pcdavid** [eclipse-emf-parsley/emf-parsley#93]
[EMF Query](https://github.com/eclipse-emfservices/emf-query) has been unmaintained for a while. I'd like to drop it [from the SimRel](https://github.com/eclipse-simrel/simrel.build/blob/main/emf-services.aggrcon#L3) but EMF Parsley still depends on it.

AFAICT, it's not actually *used* anywhere, but it is referenced in the target platforms and Oomph setup, and `org.eclipse.emf.parsley.cdo.common` declares an (unused) dependency on it.

**Comment by LorenzoBettini** [comment]
Thanks, I'll try removing that.

**Comment by LorenzoBettini** [comment]
@pcdavid a milestone 1.17.0 without emf query is already part of the current 2024-06 simrel repository

**Comment by pcdavid** [comment]
Thank you for the quick response time!

**Comment by merks** [comment]
Indeed this breaks EPP because SimRel is not a closed universe and is not the only place with dependencies.

**Comment by LorenzoBettini** [comment]
@merks sorry, I didn't know this could break EPP. @pcdavid notified me about the unused dependency, so I thought it would be safe.

Should I do anything from my side?

I can only confirm that we don't use EMF Query in Parsley; maybe it ended up there at the beginning for some experiments,

**Comment by pcdavid** [comment]
> Indeed this breaks EPP because SimRel is not a closed universe and is not the only place with dependencies.

Is it the removal of the dependency in EMF Parsley (this issue) or my disabling of EMF Query from the SimRel that causes a breakage? I'll re-enable it for now.

**Comment by merks** [comment]
I removed the dependency from EPP

**Comment by pcdavid** [comment]
Thanks, I couldn't find any explicit reference to EMF Query in [the package definition](https://github.com/eclipse-packaging/packages/blob/master/packages/org.eclipse.epp.package.modeling.product/epp.product#L250) and was wondering who pulled that, but it's just that [you were too quick](https://github.com/eclipse-packaging/packages/commit/299614be47d5c7667f54f6403de40c0cb8419b4a#diff-f1145f3f96d700fe01a1bbcc60d65a4fabf2a17d2f7e2986e432c2b0a0de9134).

**Comment by merks** [comment]
Yes, I was very quick.  Thanks again for your responsiveness!
